language: python

dist: focal

matrix:
  include:
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - git
          - build-essential
          - automake
          - libtool
          - python-dev
          - gettext
          - swig
    env:
      - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8 && PYTHON=2.7"

python:
  - "2.7"

git:
  depth: 1

before_install:
  - eval "${MATRIX_EVAL}"
  - pyenv global 3.8
  - pip3 install --upgrade pip tox six


script:
- echo "compiling oe-alliance plugins"
- autoreconf -i
- ./configure
- make
- python -m compileall .
- echo done!
